"""Parametric OpenSCAD source generators.

Unlike the STL meshes, these emit *editable* parametric models: every
dimension is a named variable at the top of the file, so the user can open the
``.scad`` in OpenSCAD (or import into FreeCAD) and keep iterating on the design
that the simulator produced.
"""

from __future__ import annotations

from ..sim.grain import Grain, GrainType
from ..sim.motor import Nozzle


def grain_scad(grain: Grain) -> str:
    bore = grain.core_diameter if grain.grain_type == GrainType.BATES else 0.0
    return f"""// Parametric solid-propellant grain (generated by SzymonZimnyprog sim)
// All dimensions in millimetres.

outer_diameter = {grain.outer_diameter * 1000:.3f};
core_diameter  = {bore * 1000:.3f};
segment_length = {grain.segment_length * 1000:.3f};
segments       = {grain.segments};
segment_gap    = 3;        // inter-segment spacer, editable
$fn = 128;

module grain_segment() {{
    difference() {{
        cylinder(h = segment_length, d = outer_diameter);
        if (core_diameter > 0)
            translate([0, 0, -1])
                cylinder(h = segment_length + 2, d = core_diameter);
    }}
}}

for (i = [0 : segments - 1])
    translate([0, 0, i * (segment_length + segment_gap)])
        grain_segment();
"""


def nozzle_scad(nozzle: Nozzle, chamber_diameter: float | None = None) -> str:
    rt = nozzle.throat_diameter / 2.0
    re = rt * (nozzle.expansion_ratio ** 0.5)
    rc = (chamber_diameter / 2.0) if chamber_diameter else rt * 3.0
    return f"""// Parametric converging-diverging nozzle (generated)
// All dimensions in millimetres.

throat_diameter  = {nozzle.throat_diameter * 1000:.3f};
exit_diameter    = {2 * re * 1000:.3f};
chamber_diameter = {2 * rc * 1000:.3f};
conv_half_angle  = 45;     // degrees, editable
div_half_angle   = 15;     // degrees, editable
wall_thickness   = {max(rt * 0.25, 0.003) * 1000:.3f};
$fn = 128;

throat_r = throat_diameter / 2;
exit_r   = exit_diameter / 2;
cham_r   = chamber_diameter / 2;

conv_len = (cham_r - throat_r) / tan(conv_half_angle);
div_len  = (exit_r - throat_r) / tan(div_half_angle);

module nozzle() {{
    rotate_extrude($fn = 128)
        polygon(points = [
            [cham_r, 0],
            [throat_r, conv_len],
            [exit_r, conv_len + div_len],
            [exit_r + wall_thickness, conv_len + div_len],
            [throat_r + wall_thickness, conv_len],
            [cham_r + wall_thickness, 0],
        ]);
}}

nozzle();
"""


def airframe_scad(body_diameter: float, body_length: float,
                  nose_length: float, fin_count: int = 4,
                  fin_span: float = 0.12, fin_root: float = 0.25) -> str:
    return f"""// Parametric missile airframe: nose cone + body + fins (generated)
// All dimensions in millimetres.

body_diameter = {body_diameter * 1000:.3f};
body_length   = {body_length * 1000:.3f};
nose_length   = {nose_length * 1000:.3f};
fin_count     = {fin_count};
fin_span      = {fin_span * 1000:.3f};
fin_root      = {fin_root * 1000:.3f};
fin_tip       = fin_root * 0.4;
fin_thickness = body_diameter * 0.06;
$fn = 128;

body_r = body_diameter / 2;

module nose_cone() {{
    // ogive approximation via stacked truncated cones
    translate([0, 0, body_length])
        cylinder(h = nose_length, r1 = body_r, r2 = 1);
}}

module body() {{ cylinder(h = body_length, r = body_r); }}

module fin() {{
    linear_extrude(height = fin_thickness, center = true)
        polygon(points = [
            [0, 0], [0, fin_root],
            [fin_span, fin_root * 0.5 + fin_tip * 0.5],
            [fin_span, fin_root * 0.5 - fin_tip * 0.5],
        ]);
}}

module fins() {{
    for (i = [0 : fin_count - 1])
        rotate([0, 0, i * 360 / fin_count])
            translate([body_r, 0, 0])
                rotate([90, 0, 0])
                    fin();
}}

union() {{ body(); nose_cone(); fins(); }}
"""
