"""Export simulation results for MATLAB/Simulink consumption.

Three artefacts:

* ``thrust_curve_csv``     -- time, thrust, pressure, mass-flow columns;
* ``rasp_eng``             -- RASP ``.eng`` motor file (read by OpenRocket,
  RASAero, ThrustCurve.org, and importable into Simulink via ``readmatrix``);
* ``trajectory_csv``       -- engagement/flight time histories;
* ``matlab_driver``        -- a ``.m`` script that calls the live REST API with
  ``webwrite`` and lands the results in the MATLAB workspace as timeseries,
  ready for ``From Workspace`` blocks.
"""

from __future__ import annotations

from ..sim.motor import MotorResult


def thrust_curve_csv(res: MotorResult) -> str:
    lines = ["time_s,thrust_N,chamber_pressure_Pa,mass_flow_kgps"]
    for i in range(len(res.time)):
        lines.append(
            f"{res.time[i]:.6f},{res.thrust[i]:.4f},"
            f"{res.chamber_pressure[i]:.2f},{res.mass_flow[i]:.6f}"
        )
    return "\n".join(lines) + "\n"


def rasp_eng(res: MotorResult, *, name: str, diameter_mm: float,
             length_mm: float, propellant_mass: float,
             total_mass: float, manufacturer: str = "SzymonZimnyprog") -> str:
    """RASP .eng motor definition.

    Header: name dia(mm) len(mm) delays prop_mass(kg) total_mass(kg) maker
    Then ``time thrust`` pairs (thrust strictly after t=0).
    """
    header = (
        f"{name} {diameter_mm:.1f} {length_mm:.1f} P "
        f"{propellant_mass:.4f} {total_mass:.4f} {manufacturer}"
    )
    lines = [
        "; Generated by SzymonZimnyprog interceptor/motor simulator",
        f"; Total impulse {res.total_impulse:.1f} N*s (class {res.impulse_class}),"
        f" Isp {res.specific_impulse:.1f} s",
        header,
    ]
    for i in range(len(res.time)):
        t, f = res.time[i], res.thrust[i]
        if t <= 0.0:
            continue
        lines.append(f"   {t:.4f} {max(f, 0.0):.3f}")
    return "\n".join(lines) + "\n"


def trajectory_csv(result: dict) -> str:
    """CSV from a trajectory/engagement result dict (whichever keys exist)."""
    time = result.get("time", [])
    if "interceptor_position" in result:
        header = ("time_s,int_x,int_y,int_z,tgt_x,tgt_y,tgt_z,"
                  "separation_m,int_speed_mps,tgt_speed_mps,accel_cmd_mps2")
        rows = [header]
        ip = result["interceptor_position"]
        tp = result["target_position"]
        sep = result["separation"]
        isp = result["interceptor_speed"]
        tsp = result["target_speed"]
        acc = result["interceptor_accel_cmd"]
        for i in range(len(time)):
            rows.append(
                f"{time[i]:.4f},{ip[i][0]:.3f},{ip[i][1]:.3f},{ip[i][2]:.3f},"
                f"{tp[i][0]:.3f},{tp[i][1]:.3f},{tp[i][2]:.3f},"
                f"{sep[i]:.3f},{isp[i]:.3f},{tsp[i]:.3f},{acc[i]:.3f}"
            )
        return "\n".join(rows) + "\n"

    header = "time_s,x,y,z,speed_mps,mach,mass_kg,altitude_m"
    rows = [header]
    pos = result.get("position", [])
    spd = result.get("speed", [])
    mach = result.get("mach", [])
    mass = result.get("mass", [])
    alt = result.get("altitude", [])
    for i in range(len(time)):
        rows.append(
            f"{time[i]:.4f},{pos[i][0]:.3f},{pos[i][1]:.3f},{pos[i][2]:.3f},"
            f"{spd[i]:.3f},{mach[i]:.4f},{mass[i]:.4f},{alt[i]:.3f}"
        )
    return "\n".join(rows) + "\n"


def matlab_driver(base_url: str = "http://localhost:8000") -> str:
    """A .m script driving the REST API and exporting timeseries to Simulink."""
    return f"""function out = szymon_sim_driver(varargin)
%SZYMON_SIM_DRIVER  Call the interceptor/motor simulator REST API from MATLAB.
%
%   out = szymon_sim_driver()                  % default motor + engagement
%   out = szymon_sim_driver('motor', req)      % custom motor request struct
%   out = szymon_sim_driver('engagement', req) % custom engagement struct
%
%   The returned struct contains MATLAB timeseries objects ready for use in
%   Simulink "From Workspace" blocks (e.g. assignin('base','thrust_ts',...)).

    base = "{base_url}";
    mode = "motor";
    req = struct();
    if nargin >= 1, mode = string(varargin{{1}}); end
    if nargin >= 2, req = varargin{{2}}; end
    opts = weboptions('MediaType', 'application/json', 'Timeout', 120);

    switch mode
        case "motor"
            r = webwrite(base + "/api/motor/simulate", req, opts);
            t = r.time(:);
            out.thrust_ts   = timeseries(r.thrust(:), t);
            out.pressure_ts = timeseries(r.chamber_pressure(:), t);
            out.summary     = r.summary;
        case "missile"
            r = webwrite(base + "/api/missile/simulate", req, opts);
            t = r.time(:);
            pos = cell2mat(cellfun(@(c) c(:)', r.position, 'uni', 0));
            out.position_ts = timeseries(pos, t);
            out.speed_ts    = timeseries(r.speed(:), t);
            out.summary     = r.summary;
        case "engagement"
            r = webwrite(base + "/api/engagement/simulate", req, opts);
            t = r.time(:);
            ip = cell2mat(cellfun(@(c) c(:)', r.interceptor_position, 'uni', 0));
            tp = cell2mat(cellfun(@(c) c(:)', r.target_position, 'uni', 0));
            out.interceptor_ts = timeseries(ip, t);
            out.target_ts      = timeseries(tp, t);
            out.separation_ts  = timeseries(r.separation(:), t);
            out.summary        = r.summary;
        otherwise
            error("Unknown mode: %s", mode);
    end

    % Publish to base workspace for Simulink From Workspace blocks.
    fn = fieldnames(out);
    for i = 1:numel(fn)
        assignin('base', fn{{i}}, out.(fn{{i}}));
    end
end
"""
